from os import getenv

MYSQL_HOST = getenv("MYSQL_HOST")
MYSQL_USER = getenv("MYSQL_USER")
MYSQL_PASSWORD = getenv("MYSQL_PASSWORD")
MYSQL_DB = getenv("MYSQL_DB")
SECRET_KEY = getenv("SECRET_KEY")

CLOUDINARY_URL = getenv("CLOUDINARY_URL")
CLOUD_NAME = getenv("CLOUD_NAME")
API_KEY = getenv("API_KEY")
API_SECRET = getenv("API_SECRET")
CLOUDINARY_FOLDER = getenv("CLOUDINARY_FOLDER")

